module.exports = [
  {
    name: 'eightOunce',
    script: 'dist/src/clients/eightOunceClient.js',
    time: true,
    cron: '0 * * * *',
  },
  {
    name: 'monogram',
    script: 'dist/src/clients/monogramClient.js',
    time: true,
    cron: '0 * * * *',
  },
  {
    name: 'pirates',
    script: 'dist/src/clients/piratesClient.js',
    time: true,
    cron: '0 * * * *',
  },
  {
    name: 'revolver',
    script: 'dist/src/clients/revolverClient.js',
    time: true,
    cron: '0 * * * *',
  },
  {
    name: 'rogueWave',
    script: 'dist/src/clients/rogueWaveClient.js',
    time: true,
    cron: '0 * * * *',
  },
  {
    name: 'rosso',
    script: 'dist/src/clients/rossoClient.js',
    time: true,
    cron: '0 * * * *',
  },
  {
    name: 'subtext',
    script: 'dist/src/clients/subtextClient.js',
    time: true,
    cron: '0 * * * *',
  },
  {
    name: 'hatch',
    script: 'dist/src/clients/hatchClient.js',
    time: true,
    cron: '0 * * * *',
  },
  {
    name: 'library',
    script: 'dist/src/clients/libraryClient.js',
    time: true,
    cron: '0 * * * *',
  },
  {
    name: 'pallet',
    script: 'dist/src/clients/palletClient.js',
    time: true,
    cron: '0 * * * *',
  },
  {
    name: 'luna',
    script: 'dist/src/clients/lunaClient.js',
    time: true,
    cron: '0 * * * *',
  },
  {
    name: 'angryRoaster',
    script: 'dist/src/clients/angryRoasterClient.js',
    time: true,
    cron: '0 * * * *',
  },
  {
    name: 'prototype',
    script: 'dist/src/clients/prototypeClient.js',
    time: true,
    cron: '0 * * * *',
  },
  {
    name: 'quietly',
    script: 'dist/src/clients/quietlyClient.js',
    time: true,
    cron: '0 * * * *',
  },
  {
    name: 'social',
    script: 'dist/src/clients/socialClient.js',
    time: true,
    cron: '0 * * * *',
  },
  {
    name: 'sorellina',
    script: 'dist/src/clients/sorellinaClient.js',
    time: true,
    cron: '0 * * * *',
  },
  {
    name: 'prodigal',
    script: 'dist/src/clients/prodigalClient.js',
    time: true,
    cron: '0 * * * *',
  },
  {
    name: 'nemesis',
    script: 'dist/src/clients/nemesisClient.js',
    time: true,
    cron: '0 * * * *',
  },
  {
    name: 'timbertrain',
    script: 'dist/src/clients/timbertrainClient.js',
    time: true,
    cron: '0 * * * *',
  },
  {
    name: 'zabCafe',
    script: 'dist/src/clients/zabCafeClient.js',
    time: true,
    cron: '0 * * * *',
  },
  {
    name: 'philAndSebastian',
    script: 'dist/src/clients/philAndSebastianClient.js',
    time: true,
    cron: '0 * * * *',
  },
  {
    name: 'thomBargen',
    script: 'dist/src/clients/thomBargenClient.js',
    time: true,
    cron: '0 * * * *',
  },
  {
    name: 'transcend',
    script: 'dist/src/clients/transcendClient.js',
    time: true,
    cron: '0 * * * *',
  },
];
