export enum BaseUrl {
  EightOunce = 'https://eightouncecoffee.ca',
  Hatch = 'https://www.hatchcrafted.com',
  LibrarySpecialtyCoffee = 'https://thelibraryspecialtycoffee.com',
  Luna = 'https://enjoylunacoffee.com',
  Monogram = 'https://monogramcoffee.com',
  Pallet = 'https://palletcoffeeroasters.com',
  PiratesOfCoffee = 'https://piratesofcoffee.com',
  Prodigal = 'https://getprodigal.com',
  Prototype = 'https://www.prototypecoffee.ca',
  Quietly = 'https://www.quietlycoffee.com',
  Revolver = 'https://revolvercoffee.ca',
  RogueWave = 'https://roguewavecoffee.ca',
  Rosso = 'https://rossocoffeeroasters.com',
  Social = 'https://socialcoffeeroasters.ca',
  Sorellina = 'https://sorellina.ca',
  Subtext = 'https://subtext.coffee',
  TheAngryRoaster = 'https://theangryroaster.com',
}
