export enum Vendor {
  EightOunce = 'Eight Ounce Coffee',
  Hatch = 'Hatch Coffee Roasters',
  Library = 'Library Specialty Coffee',
  Luna = 'Luna Coffee',
  Monogram = 'Monogram Coffee',
  Nemesis = 'Nemesis Coffee',
  Pallet = 'Pallet Coffee Roasters',
  Pirates = 'Pirates of Coffee',
  Prodigal = 'Prodigal',
  Prototype = 'Prototype Coffee',
  Quietly = 'Quietly Coffee',
  RabbitHole = 'Rabbit Hole Roasters',
  Revolver = 'Revolver Coffee',
  RogueWave = 'Rogue Wave Coffee',
  Rosso = 'Rosso Coffee',
  Social = 'Social Coffee Roasters',
  Sorellina = 'Sorellina Coffee',
  Subtext = 'Subtext Coffee Roasters',
  TheAngryRoaster = 'The Angry Roaster Coffee Co.',
}
