export enum VendorApiUrl {
  AngryRoaster = 'https://www.theangryroaster.com/collections/all/products.json?limit=250',
  EightOunce = 'https://eightouncecoffee.ca/collections/newest-coffee/products.json?limit=250',
  Library = 'https://www.thelibraryspecialtycoffee.com/collections/frontpage/products.json?limit=250',
  Luna = 'https://enjoylunacoffee.com/wp-json/wp/v2/product?product_cat=16&per_page=100',
  Monogram = 'https://monogramcoffee.com/collections/whole-bean-coffee/products.json?limit=250',
  Nemesis = 'https://www.nemesis.coffee/collections/shop-coffee/products.json?limit=250',
  Pallet = 'https://palletcoffeeroasters.com/collections/coffee/products.json?limit=250',
  Pirates = 'https://piratesofcoffee.com/collections/coffee/products.json?limit=250',
  Prodigal = 'https://getprodigal.com/collections/87-pt-coffees/products.json?limit=250',
  Prototype = 'https://www.prototypecoffee.ca/shop?format=json-pretty',
  Quietly = 'https://www.quietlycoffee.com/collections/our-coffee/products.json?limit=250',
  Revolver = 'https://revolvercoffee.ca/collections/coffee/products.json?limit=250',
  RogueWave = 'https://www.roguewavecoffee.ca/collections/coffee/products.json?limit=250',
  Rosso = 'https://www.rossocoffeeroasters.com/collections/coffee/products.json?limit=250',
  Social = 'https://www.socialcoffeeroasters.ca/collections/coffee/products.json?limit=250',
  Sorellina = 'https://www.sorellina.ca/collections/beans/products.json?limit=250',
  Subtext = 'https://www.subtext.coffee/collections/filter-coffee-beans/products.json?limit=250',
}
